service: fire-alerts

provider:
  name: aws
  runtime: python2.7
  timeout: 300
  profile: palm
  memorySize: 3008
  region: 'us-east-1'
  role: arn:aws:iam::838255262149:role/lambda_basic_execution
  deploymentBucket: palm-risk-poc
  iamRoleStatements:
    - Effect: "Allow"
      Action:
         - "s3:*"
      Resource:
         - 'arn:aws:s3:::palm-risk-poc'

package:
  artifact: lambda-deploy.zip

functions:
  fire-alerts:
    handler: handler.fire_alerts
    events:
        - http:
            path: fire-alerts
            method: post
            cors: true

  fire-analysis:
    handler: handler.fire_analysis
    events:
        - http:
            path: fire-analysis
            method: post
            cors: true
    
  validate-layer-extent:
    handler: handler.validate_layer_extent
    events:
        - http:
            path: validate-layer-extent
            method: post
            cors: true

  bulk-fire-upload:
    handler: handler.bulk_fire_upload

  update-fire-tile:
    handler: handler.update_fire_tile

  nightly-fires-update:
    handler: handler.nightly_fires_update
    events:
      - schedule: 
          # run at 5:05 UTC (12:05 or 1:05 EDT, depending on daylight savings)
          rate: cron(5 5 * * ? *) 
          input:
            fire_type: VIIRS
        # run at 5:15 UTC
      - schedule:
          rate: cron(15 5 * * ? *)
          input:
            fire_type: MODIS


